data<-read.table("household_power_consumption.txt",nrows = 2075259,sep=";",header=TRUE,na.strings = "?")
library(lubridate)
twodays<-subset(data,Date=="2007-02-01"|Date=="2007-02-02")
png(filename = "plot1.png", width = 480, height = 480)
hist(twodays$Global_active_power,col="red",xlab = "Global Active Power (kilowatts)",main = "Global Active Power")
dev.off()